### ISSUE TITLE
fhead doesn't work.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#107]
Need to add the 'fhead' ability to vcp and vcat commands.   fhead is part of the commands that /data understands some some effort might be needed to get fhead to work on VOSpace commands.

This is a high priority item.

**Comment by brianmajor** [comment]
As JJ says, this VOSpace fhead call to the data web service will work:

curl -v -L "http://www.canfar.phys.uvic.ca/data/pub/VOSpace/CADCAuthtest1/700000o.fits.fz?fhead=true"

but this will also work, straight to vospace:

curl -v -L "http://www.canfar.phys.uvic.ca/vospace/synctrans?TARGET=vos%3A%2F%2Fcadc.nrc.ca~vospace%2FCADCAuthtest1%2F700000o.fits.fz&DIRECTION=pullFromVoSpace&PROTOCOL=ivo%3A%2F%2Fivoa.net%2Fvospace%2Fcore%23httpget&fhead=true"

So, I don't think there's a server-side component to this change. 

The 'wcs=true' parameter will also work.
