### ISSUE TITLE
Link listing doesn't work? 

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#171]
(base) woodpecker:~ kavelaarsj$ vls vos:OSSOS/dbimages/calibrators/
calibrators
(base) woodpecker:~ kavelaarsj$ vls -l vos:OSSOS/dbimages/calibrators/
lrw-rw-r--  jkavelaars_077       ivo://cadc.nrc.ca/gms#OSSOS ivo://cadc.nrc.ca/gms#OSSOS-Admin                    0 May 25  2016 calibrators -> vos://cadc.nrc.ca!vault/sgwyn/flats
(base) woodpecker:~ kavelaarsj$

**Comment by andamian** [comment]
@ijiraq just to clarify: you'd expect that `vis` would follow the internal links?

**Comment by ijiraq** [comment]
> @ijiraq just to clarify: you'd expect that `vis` would follow the internal links?

Yes.  `vls vos:rootNode/link` should list the contents of what `link` points to which might be a container.    I think this used to work.

JJ
