### ISSUE TITLE
the version of the scripts should be unique.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#30]
Currently scripts pull their version number from the library.  Actually, the scripts have their own version increments and should check that they are pulling in the library version they are meant to go with ..  This is needed since the scripts / applications are separate entities and even when one installs the new package one sometimes ends-up with the old script calling the new library.

**Comment by ijiraq** [comment]
This could be achieved by moving the CLI to be modules inside the vos package and use the setup.py command_process attribute to create the executables.  

When doing this sort of migration we should be sure to alert users to remove their old 'v*' commands by doing a pip uninstall first.

**Comment by ijiraq** [comment]
looks like we don't need to alert the users as the v* commands are overwritten.

**Comment by andamian** [comment]
With the scripts implemented as entry_points, they are now part of the library and cannot be installed separately. Sharing the version of the library is not an issue anymore.
