### ISSUE TITLE
VOFS cache can be/is stale when external copies occur.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#32]
Below is shell history that demonstrates this issue.

<pre>
mach87:~ jjk$ mountvofs --vospace vos:jkavelaars --mountpoint ${HOME}/jkavelaars
mach87:~ jjk$ cp ${HOME}/jkavelaars/script.sh ./
mach87:~ jjk$ head script.sh 
#!/bin/bash
# a script

source ${HOME}/.bash_profile

exp1=$1
exp2=$2
exp3=$3
ccd=$4
mach87:~ jjk$ diff ${HOME}/jkavelaars/script.sh script.sh 
mach87:~ jjk$ rm ${HOME}/jkavelaars/script.sh 
mach87:~ jjk$ vi script.shmach87:~ jjk$ head script.sh 
#!/bin/bash
# a script
JUNK

source ${HOME}/.bash_profile

exp1=$1
exp2=$2
exp3=$3
ccd=$4
mach87:~ jjk$ vcp script.sh vos:jkavelaars/
mach87:~ jjk$ diff ${HOME}/jkavelaars/script.sh script.sh 
2a3
> JUNK
mach87:~ jjk$ 
mach87:~ jjk$ vcat vos:jkavelaars/script.sh | head
#!/bin/bash
# a script
JUNK

source ${HOME}/.bash_profile

exp1=$1
exp2=$2
exp3=$3
ccd=$4
</pre>

##### 

Oops.   Why didn't the rm clear the cached version of the file?

JJ

**Comment by andamian** [comment]
Can't reproduce this anymore. Presumably fixed.
