### ISSUE TITLE
vos does not work on public vospaces with expired proxy certs

### ISSUE THREAD

**Issue by sfabbro** [opencadc/vostools#53]
How to reproduce:
1. Install vos-1.12.2
2. Somehow get an expired proxy, or wait 1.1 day with getCert --daysValid=1
3. List a public VOSpace:

```
vls vos:sfabbro
 vos: [Errno 1] _ssl.c:499: error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired
vls: _ssl.c:499: error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired
```
1. Realize when you remove .ssl/cadcproxy.pem that it works.

**Comment by ijiraq** [comment]
Did it use to?

JJ
