### ISSUE TITLE
mountvofs not working in batch jobs in latest release

### ISSUE THREAD

**Issue by e-koch** [opencadc/vostools#54]
The line:
`mountvofs --vospace vos:MWSynthesis/ --mountpoint ${TMPDIR}/vos --cache_dir ${TMPDIR}/vos_cache`
no longer works when used in a batch job and produces no error in the log. When checked, the mountpoint is empty.  `getCert` runs without errors earlier in the script.

It does work in the batch environment when using an older release. It also works fine when running in an interactive environment (with the newest release).

**Comment by ijiraq** [comment]
Hi Eric,

That’s a very odd error.  I’m not sure that this is directly related to vos but like some interaction between the environment and the application that used to work and now doesn’t.   What the might be is not immediately obvious to me.

Although its rather a pain.   Could you try running the mountvofs command in your batch environment with the --debug option turned on and then send the output of the error log (should be in /tmp/vos.err and also the stdout (which condor will likely capture for you).    Seeing those together might help me see what’s going on and if there is some where that vos can be modified to make the problem you are having go away.


JJ

**Comment by ijiraq** [comment]
No feedback from user in issue so closing.
