### ISSUE TITLE
ERROR vls bad handshake

### ISSUE THREAD

**Issue by Mikea1985** [opencadc/vostools#58]
I installed the `vos` package using pip earlier today. 
I have run `getCert` to get certificates in order; that worked fine. 
But upon running `vls` or `vcp`, I get an error message. 

```
$ vls vos:OSSOS/
ERROR vls bad handshake: Error([('SSL routines', 'SSL3_READ_BYTES', 'tlsv1 alert unknown ca')],)
```

I get the same error message when trying to use `vcp`. 
I have `openssl` and `pyopenssl` installed and up to date. 
I have tried googling this error message and subparts of it, but I'm not finding anything that looks like this, so I suspect it is an error from `vos` and not from `openssl`. 

Any suggestions to possible solutions?

**Comment by ijiraq** [comment]
resolved in commit opencadc/cadctools#33
